<?php
class Emailing {
    const PASSWORD_RESET = "PASSWORD_RESET";
    const INVITE = "INVITE";
    const SIGNUP = "SIGNUP";
    const FINANCE_APPLICATION_UPDATE = "FINANCE_APPLICATION_UPDATE";
    const FINANCE_APPLICATION_SUBMISSION = "FINANCE_APPLICATION_SUBMISSION";
    const WILDCARD = "WILDCARD"; // ??
}

?>