<?php
class Emailing {
    const PASSWORD_RESET = "PASSWORD_RESET";
    const INVITE = "INVITE";
    const SIGNUP = "SIGNUP";
    const NEW_MESSAGE_UPDATE = "NEW_MESSAGE_UPDATE";
    const FINANCE_APPLICATION_UPDATE = "FINANCE_APPLICATION_UPDATE";
    const FINANCE_APPLICATION_SUBMISSION = "FINANCE_APPLICATION_SUBMISSION";
    const WILDCARD = "WILDCARD"; // ??
}

class GrowAgricRoles {
    const ADMINS = "ADMINS";
    const FIELDAGENTS = "FIELDAGENTS";
    const FARMERS = "FARMERS";
}

?>